[package]
name = "powdoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive", "cargo"] }
env_logger = "0.11.2"
inquire = "0.6.2"
log = "0.4.20"
sailfish = "0.8.3"
serde = { version = "1.0.196", features = ["derive"] }
serde_repr = "0.1.18"
serde_yaml = "0.9.31"
