name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --locked --quiet

    - name: Install
      run: cargo install --path . --locked --quiet

    - name: Install Expect
      run: sudo apt-get install -y expect

    - name: Run tests
      run: cargo test --locked --quiet
